---
- name: Setup nginx with SSL
  hosts: tensor
  become: yes
  become_method: sudo
  gather_facts: true
  tags: [https]
  tasks:
    - name: open tcp-443 on firewalld and copy ssl-conf files to nginx directory
      firewalld:
        zone: public
        port: 443/tcp
        permanent: true
        state: enabled
    - copy:
        src: files/ssl-params.conf
        dest: /etc/nginx/conf.d/ssl-params.conf
        owner: root
        group: root
        mode: 0644
    - copy:
        src: files/localhost.conf
        dest: /etc/nginx/conf.d/localhost.conf
        owner: root
        group: root
        mode: 0644
            
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Wait for Nginx
      wait_for:
        port: 443

